// <auto-generated />
using System;
using ConstructionExpenseManager.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConstructionExpenseManager.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708175634_RemoveOfficeProtocolPercentFromTender")]
    partial class RemoveOfficeProtocolPercentFromTender
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConstructionExpenseManager.Api.Models.CommissionWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BilledGst")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("CommissionPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ExtraGstBill")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("GstAmount")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("GstBillCommission")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("TenderWorkAmount")
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("CommissionWorks");
                });

            modelBuilder.Entity("ConstructionExpenseManager.Api.Models.GstVendorEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CommissionPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GstBillAmount")
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("date");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("WorkId")
                        .HasColumnType("integer");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("WorkType", "WorkId");

                    b.ToTable("GstVendorEntries");
                });

            modelBuilder.Entity("ConstructionExpenseManager.Api.Models.GstVendorRepayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountReceived")
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GstVendorEntryId")
                        .HasColumnType("integer");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GstVendorEntryId");

                    b.ToTable("GstVendorRepayments");
                });

            modelBuilder.Entity("ConstructionExpenseManager.Api.Models.PrivateWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AreaSqft")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RatePerSqft")
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("PrivateWorks");
                });

            modelBuilder.Entity("ConstructionExpenseManager.Api.Models.PrivateWorkCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AgreedTotalAmount")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PrivateWorkId")
                        .HasColumnType("integer");

                    b.Property<string>("RateBasis")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("PrivateWorkId");

                    b.ToTable("PrivateWorkCategories");
                });

            modelBuilder.Entity("ConstructionExpenseManager.Api.Models.PrivateWorkCategoryPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(14,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<string>("Remarks")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("PrivateWorkCategoryPayments");
                });

            modelBuilder.Entity("ConstructionExpenseManager.Api.Models.PrivateWorkMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<int>("PrivateWorkId")
                        .HasColumnType("integer");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("PrivateWorkId");

                    b.ToTable("PrivateWorkMaterials");
                });

            modelBuilder.Entity("ConstructionExpenseManager.Api.Models.PrivateWorkMilestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("date");

                    b.Property<decimal>("PercentOfTotal")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("PrivateWorkId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PrivateWorkId");

                    b.ToTable("PrivateWorkMilestones");
                });

            modelBuilder.Entity("ConstructionExpenseManager.Api.Models.TenderRaBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("date");

                    b.Property<decimal>("BilledAmount")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("CorporatorCommissionPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("OfficerCommissionPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("RaBillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TenderWorkId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenderWorkId");

                    b.ToTable("TenderRaBills");
                });

            modelBuilder.Entity("ConstructionExpenseManager.Api.Models.TenderWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BilledGst")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("CorporatorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("CorporatorProtocolPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ExtraGstBill")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("GstBillCommission")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("GstTotal")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("NameOfWork")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("SecurityDepositPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TenderAmount")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("TenderEMD")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("TenderFee")
                        .HasColumnType("decimal(14,2)");

                    b.Property<decimal>("TenderFilingAmount")
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("TenderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("WorkExpenditure")
                        .HasColumnType("decimal(14,2)");

                    b.HasKey("Id");

                    b.ToTable("TenderWorks");
                });

            modelBuilder.Entity("ConstructionExpenseManager.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("MobileNumber")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ConstructionExpenseManager.Api.Models.GstVendorRepayment", b =>
                {
                    b.HasOne("ConstructionExpenseManager.Api.Models.GstVendorEntry", "GstVendorEntry")
                        .WithMany("Repayments")
                        .HasForeignKey("GstVendorEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GstVendorEntry");
                });

            modelBuilder.Entity("ConstructionExpenseManager.Api.Models.PrivateWorkCategory", b =>
                {
                    b.HasOne("ConstructionExpenseManager.Api.Models.PrivateWork", "PrivateWork")
                        .WithMany("Categories")
                        .HasForeignKey("PrivateWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrivateWork");
                });

            modelBuilder.Entity("ConstructionExpenseManager.Api.Models.PrivateWorkCategoryPayment", b =>
                {
                    b.HasOne("ConstructionExpenseManager.Api.Models.PrivateWorkCategory", "Category")
                        .WithMany("Payments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ConstructionExpenseManager.Api.Models.PrivateWorkMaterial", b =>
                {
                    b.HasOne("ConstructionExpenseManager.Api.Models.PrivateWork", "PrivateWork")
                        .WithMany("Materials")
                        .HasForeignKey("PrivateWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrivateWork");
                });

            modelBuilder.Entity("ConstructionExpenseManager.Api.Models.PrivateWorkMilestone", b =>
                {
                    b.HasOne("ConstructionExpenseManager.Api.Models.PrivateWork", "PrivateWork")
                        .WithMany("Milestones")
                        .HasForeignKey("PrivateWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrivateWork");
                });

            modelBuilder.Entity("ConstructionExpenseManager.Api.Models.TenderRaBill", b =>
                {
                    b.HasOne("ConstructionExpenseManager.Api.Models.TenderWork", "TenderWork")
                        .WithMany("RaBills")
                        .HasForeignKey("TenderWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TenderWork");
                });

            modelBuilder.Entity("ConstructionExpenseManager.Api.Models.GstVendorEntry", b =>
                {
                    b.Navigation("Repayments");
                });

            modelBuilder.Entity("ConstructionExpenseManager.Api.Models.PrivateWork", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Materials");

                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("ConstructionExpenseManager.Api.Models.PrivateWorkCategory", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("ConstructionExpenseManager.Api.Models.TenderWork", b =>
                {
                    b.Navigation("RaBills");
                });
#pragma warning restore 612, 618
        }
    }
}
